global using Application.Dtos;
global using Application.Exceptions;
global using Application.Extensions;
global using Domain.Models;
global using Domain.ValueObjects;
global using Microsoft.EntityFrameworkCore;
global using Application.Data.DataBaseContext;
global using Shared.CQRS;
global using AutoMapper;